---
 - name: get_url the remote checks
   get_url:
     url: "{{ item.url }}"
     dest: "{{ nrpe_check_location }}/{{ item.name }}"
     owner: "{{ nrpe_user }}"
     group: "{{ nrpe_group }}"
     mode: "{{ nrpe_check_mode }}"
     backup: "{{ nrpe_check_backup }}"
     checksum: "{{ item.checksum }}"
   with_items: "{{ nrpe_remote_url_checks }}"
   when: nrpe_remote_url_checks.0.url != ""

 - name: copy the local checks
   copy:
     src: "{{ item.path }}"
     dest: "{{ nrpe_check_location }}/{{ item.name }}"
     owner: "{{ nrpe_user }}"
     group: "{{ nrpe_group }}"
     mode: "{{ nrpe_check_mode }}"
     backup: "{{ nrpe_check_backup }}"
   with_items: "{{ nrpe_local_checks }}"
   when: nrpe_local_checks.0.path != ""

 - name: install pip if nrpe_pip_checks.0 is not empty
   package:
     name: "{{ nrpe_python_packages }}"
     state: installed
   when: nrpe_pip_checks.0 != ""

 - name: install dependencies with pip
   pip:
     name: "{{ nrpe_pip_checks }}"
     state: present
   when: nrpe_pip_checks.0 != ""

 - name: set SELinux contexts for checks
   sefcontext:
     target: "{{ item.target }}"
     setype: "{{ item.setype }}"
     state: "{{ item.state }}"
   with_items: "{{ nrpe_check_selinux_contexts }}"
   register: set_selinux_contexts
   when: nrpe_check_selinux_contexts is defined

 - name: refresh SELinux context for checks
   command: "restorecon {{ item.target }}"
   with_items: "{{ nrpe_check_selinux_contexts }}"
   when:
     - nrpe_check_selinux_contexts is defined
     - set_selinux_contexts.changed
